name: keycloak

services:
  testkeycloak.api:
    image: ${DOCKER_REGISTRY-}testkeycloakapi
    container_name: testkeycloak.api
    build:
      context: .
      dockerfile: TestKeycloak.Api/Dockerfile
    ports:
      - 5000:8080
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - 18080:8080

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
